// Her oyun başında ara sayfada rastgele gösterilen ilham cümleleri.
export const QUOTES: string[] = [
  "Hayat, cesurlara yol verir.",
  "Dünün keşkeleri, bugünün engelleridir.",
  "Rüzgarı suçlama, yelkeni ayarla.",
  "Yaşamak basit; zor olan sade kalabilmektir.",
  "Zamana bırakma, zamanla yap.",
  "Derin olan su sessiz akar.",
  "Gölgesini unutan ağaç kurur.",
  "Kökü güçlü olanı fırtına deviremez.",
  "Her son, başka bir başlangıcın tohumudur.",
  "Hayat, iz bırakanların hikayesidir.",
  "Gözünü yıldızlara dik, ayakların yere bassın.",
  "Sessizlik, bazen en güçlü çığlıktır.",
  "Yarınlar, bugünden hazırlananlarındır.",
  "Karanlıktan şikayet edeceğine bir mum yak.",
  "Bir insanı tanıman için sonunu bekle.",
  "Yolu açık olanın zihni nettir.",
  "Geçmiş bir ders, gelecek bir fırsattır.",
  "Yolculuk, varılacak yerden daha değerlidir.",
  "Hayat bir aynadır; ne verirsen onu yansıtır.",
  "En büyük zafer, kendine hakim olmaktır.",
  "Kalbi temiz olanın yolu daima açık olur.",
  "Küçük adımlar, büyük mesafeler katettirir.",
  "Düşünce bir tohumdur; ne ekersen onu biçersin.",
  "Hayatı anlamak için geriye, yaşamak için ileriye bakılmalıdır.",
  "Bir adımla başlayan yolculuk bin mil sürer.",
  "Yaşadığın gün, sahip olduğun tek hazinedir.",
  "Huzur, iç dünyanı dış dünyadan korumaktır.",
  "Her gecenin bir sabahı, her zorluğun bir kolaylığı vardır.",
  "Doğru yolda yürüyen yorulmaz.",
  "Hayat bir nehirdir; akıntıya karşı yüzmek güç ister.",
  "Büyük dağların fırtınası da büyük olur.",
  "Sabır, acı bir kökten doğan tatlı bir meyvedir.",
  "Mutluluk gittiğin yoldadır, varış noktasında değil.",
  "Bir insanın gerçek boyu, karakteridir.",
  "Yüreği güzel olanın dünyası da güzel olur.",
  "Zaman en adil yargıçtır.",
  "İz bırakmak istiyorsan basılmamış yollardan yürü.",
  "Şükretmek, huzurun ilk kapısıdır.",
  "Taşın altında ezilme, taşı basamak yap.",
  "Hayat, sen planlar yaparken başından geçenlerdir.",
  "Anlamak, iyileşmenin yarısıdır.",
  "Dünün tecrübesi, bugünün feneridir.",
  "Derin düşün, sade yaşa.",
  "Gözlerin göremediğini bazen kalp hisseder.",
  "Sessiz kalmak, bazen en doğru cevaptır.",
  "Şüphe, hakikatin kapısını açar.",
  "Söz uçar, karakter kalır.",
  "Her fırtına hayatını mahvetsin diye gelmez; bazıları yolunu temizler.",
  "Başkasına fener olan kendi yolunu da aydınlatır.",
  "Yolunu değiştirmeden aynı yere varamazsın.",
  "Kendini bilen, dünyayı anlar.",
  "Gerçek özgürlük, arzularına hakim olmaktır.",
  "Yaşam, hissedene bir trajedi, düşünene bir komedidir.",
  "Işığı arayan, önce gölgeyle yüzleşir.",
  "En ağır yük, taşınmayan pişmanlıktır.",
  "Günün güzelliği, bakış açında gizlidir.",
  "Unutma, en karanlık saat sabaha en yakın olandır.",
  "İçindeki huzur, dışındaki kaosun ilacıdır.",
  "Hayat sandığın kadar uzun, göründüğü kadar kısa değildir.",
  "Zirvedekiler buraya gökten düşmedi.",
  "Yüreğinin kabul etmediği yere ayakların gitmesin.",
  "Ağacın kalitesi meyvesinden, insanın kalitesi sözünden anlaşılır.",
  "Küçük şeylerden mutlu olmayan, büyük şeyleri yönetemez.",
  "Bazen kazanmak için kaybetmek gerekir.",
  "Yolunu arayan, iz bırakır.",
  "Sakin sular kaptan yetiştirmez.",
  "Yaşam bir sanattır; tuval senin elindedir.",
  "Gerçek zenginlik, ihtiyaç duymamaktır.",
  "Ne bildiğin değil, nasıl yaşadığın önemlidir.",
  "Taş kırılır, ama altın değerini kaybetmez.",
  "Kalbinin pusulası daima doğruyu göstersin.",
  "Hayat bir rüzgardır; kimi savrulur, kimi uçmayı öğrenir.",
  "Şikayet etmek çare değil, eylem çözümdür.",
  "Zihni özgür olanın önünde engel durmaz.",
  "Güneş her gün yeniden doğar; sen de öyle yap.",
  "Dünyayı değiştirmek istiyorsan işe kendinden başla.",
  "Kendine dürüst ol ki kimse seni kandıramasın.",
  "Yolun sonu değil, yeni bir yolun başındasın.",
  "Sessizlik, ruhun dinlenme alanıdır.",
  "Gülümsemek, ruhun en kısa yoludur.",
  "Başarı, vazgeçmeyenlerin ödülüdür.",
  "Çalışmak, şansın temelidir.",
  "İmkansız, sadece zaman alır.",
  "Hayallerinin büyüklüğü, çaban kadardır.",
  "Erteleme, geleceğin hırsızıdır.",
  "Başarısızlık, daha zekice başlama fırsatıdır.",
  "Mazeret üreten, sonuç üretemez.",
  "Odaklanmak, hayırlı bir \"hayır\" demektir.",
  "Terlemeyen beden, zafere ulaşamaz.",
  "Zirve tekliktir, ama tırmanış cesaret ister.",
  "Yetenek kapıyı açar, disiplin içeride tutar.",
  "Plan yapmayan, başarısızlığı planlar.",
  "Zorluklar, gücünü test eden basamaklardır.",
  "Başarı, her gün tekrarlanan küçük disiplinlerdir.",
  "Başlamak için harika olman gerekmez, ama harika olmak için başlaman gerekir.",
  "Kazanmak, kaybetme korkusundan büyük olmalıdır.",
  "Hedefi olmayan gemiye hiçbir rüzgar yardım edemez.",
  "Yorulunca dinlenmeyi öğren, bırakmayı değil.",
  "Kaliteli bir sonuç, kaliteli bir çaba ister.",
  "Zafer, \"bitti\" denilen yerde başlar.",
  "Önüne çıkan engeller, seni hedefe yaklaştıran işaretlerdir.",
  "Büyük düşünenler, büyük izler bırakır.",
  "Risk almayan, gelişimi tadamaz.",
  "Sınırlarını zorlamayan, potansiyelini öğrenemez.",
  "Çalışmak zekayı aydınlatır.",
  "Gelecek, bugünden çalışanlara aittir.",
  "Sabır ve azim, taşı bile deler.",
  "Bir hedef belirle ve arkana bakma.",
  "Başarı tesadüf değil, tercihtir.",
  "Kolay elde edilen, çabuk kaybedilir.",
  "İnanç, hareketin benzinidir.",
  "Kendine inan, yolun yarısını geçmiş olursun.",
  "Hayallerini eyleme dökmedikçe sadece hayal kalırlar.",
  "İlerlemenin sırrı başlamaktır.",
  "Her başarısızlık bir tecrübedir.",
  "Odaklandığın şey büyür.",
  "Konfor alanı, hayallerin öldüğü yerdir.",
  "Yolculuk uzun olsa da ilk adım belirleyicidir.",
  "Küçük başarılar, büyük zaferlerin habercisidir.",
  "Azim, imkansızı imkanlı kılar.",
  "Zafer, sabredenlerin tahtıdır.",
  "Rakiplerinle değil, dünkü kendinle yarış.",
  "Başarının anahtarı tutarlılıktır.",
  "Kendine koyduğun engeller, en büyük engellerdir.",
  "Hayalin ne kadar büyükse, mücadelen o kadar asil olur.",
  "Bir şeyi gerçekten istersen bir yolunu bulursun.",
  "Yaratıcılık, cesaret gerektirir.",
  "Çok çalışmak şansı doğurur.",
  "Kalıcı zaferler, sabırlı adımlarla inşa edilir.",
  "Hedefe giden yolda yorulmak şereftir.",
  "Zamanını yöneten, hayatını yönetir.",
  "Başarısız olmaktan korkma, denememekten kork.",
  "Sürece güven, sonuç gelecektir.",
  "Büyük yapılar, küçük tuğlalarla yükselir.",
  "Disiplin, isteklerin ile hedeflerin arasındaki köprüdür.",
  "Engeller, gözünü hedeften ayırdığında gördüğün şeylerdir.",
  "Güçlü bir \"neden\", her türlü \"nasıl\"ı yener.",
  "Yarını değiştirecek olan, bugünkü eylemindir.",
  "Sıradan işleri sıra dışı bir özenle yap.",
  "Başarı bir durak değil, bir yolculuktur.",
  "Vazgeçtiğin an, gerçekten kaybettiğin andır.",
  "Zirveye giden yol diktir, ama manzarası güzeldir.",
  "Korkuyu eyleme dönüştür.",
  "Düzenli çalışma, mucizeler yaratır.",
  "Odaklan, çalış ve sabret.",
  "Kendi yolunu çizmeyen, başkasının haritasında kaybolur.",
  "Gücünü zorluklardan al.",
  "Bugün yapmadığın şey, yarın yükün olur.",
  "Kararlılık, kapıları açan anahtardır.",
  "Başarı, hazırlık ile fırsatın kesiştiği yerdir.",
  "Tutku, başarının motorudur.",
  "Yolun açık olsun istiyorsan adımlarını sağlam at.",
  "Sonuca değil, sürece odaklan.",
  "Büyük işler, büyük fedakarlıklar ister.",
  "Kendi ışığına güvenen, başkasının parlamasından rahatsız olmaz.",
  "Zor zamanlar güçlü insanlar yetiştirir.",
  "Kendini aşmak, en büyük başarıdır.",
  "Mükemmel anı bekleme, anı al ve mükemmel yap.",
  "Son ana kadar mücadele et.",
  "Kazananlar asla pes etmez, pes edenler asla kazanamaz.",
  "Akıllı insan, başkalarının hatalarından ders alandır.",
  "Bilgi güçtür, ama nasıl kullandığın karakterdir.",
  "Boş başak dik durur; dolu başak boyun büker.",
  "Gerçek bilgelik, neyi bilmediğini bilmektir.",
  "Dilini terbiye etmeden zihnini terbiye edemezsin.",
  "Düşünmeden konuşmak, nişan almadan ateş etmeye benzer.",
  "Sorunları, onları yaratan zihniyetle çözemezsin.",
  "Öfke gelir, göz kararır; öfke gider, yüz kızarır.",
  "Okumak, başka akıllarla düşünmektir.",
  "Bilginin kıyısında duran, derinliği anlayamaz.",
  "Dinlemek, öğrenmenin en hızlı yoludur.",
  "Eğitimsiz akıl, işlenmemiş tarla gibidir.",
  "Çok konuşan az şey söyler.",
  "Akıl, tecrübe ile bileylenir.",
  "Gerçek alçakgönüllülük, kendini bilmektir.",
  "Fikirler, dünyayı değiştiren sessiz güçlerdir.",
  "Ön yargı, gerçeğin gözünü kör eder.",
  "Bir soru sormak, bir cevaptan daha değerli olabilir.",
  "Bilen konuşmaz, konuşan her zaman bilmez.",
  "Akıl bir paraşüt gibidir; açık olmadıkça çalışmaz.",
  "Düşüncelerine dikkat et, kaderine dönüşürler.",
  "Bilgelik, yaşla değil, tecrübeyle gelir.",
  "Şüphe etmek, düşünmenin başlangıcıdır.",
  "Cahil ile tartışma, kazanamazsın.",
  "Kendi fikri olmayana, başkasının fikri yük gelir.",
  "Doğru bilgi, karanlıktaki fenerdir.",
  "Zihni eğitmek, kalbi eğitmekle başlar.",
  "Hakikat, zamanla aydınlanır.",
  "Eleştiri, gelişimin yakıtıdır.",
  "Sadece izleyen, sahnenin zorluğunu bilemez.",
  "Derinlik, yüzeyde aranmaz.",
  "Görünene aldanma, arkasındaki nedeni ara.",
  "Sabırlı insan, aklını öfkesinin önünde tutar.",
  "Değişim, zihinde başlar.",
  "En büyük cehalet, bilmediğini bilmemektir.",
  "Sözcükler keskindir; doğru seçilmelidir.",
  "Akıllı kişi, fırsatları yakalayan değil, yaratan kişidir.",
  "Anlamak, affetmenin ilk adımıdır.",
  "Gerçek güç, zihinsel dengedir.",
  "Bir fikir bir dünyayı değiştirebilir.",
  "Bilgi paylaşıldıkça çoğalır.",
  "Sorunlara takılma, çözümlere odaklan.",
  "Geçmişi değiştiremezsin, ama geleceği şekillendirebilirsin.",
  "Mantık seni A noktasından B noktasına götürür; hayal gücü her yere.",
  "Gerçeği aramak, en asil arayıştır.",
  "Büyük akıllar fikirleri, küçük akıllar kişileri tartışır.",
  "Bir kitap, elinde tuttuğun bir bahçedir.",
  "Sözün bittiği yerde tecrübe konuşur.",
  "Gözlemlemek, öğrenmenin en sessiz yoludur.",
  "Merak, keşfin annesidir.",
  "Doğru olanı yapmak, kolay olanı yapmaktan zordur.",
  "Düşünmek, ruhun kendi kendine konuşmasıdır.",
  "Önyargıları kırmak, atomu parçalamaktan zordur.",
  "Bilgeliğin temeli adalettir.",
  "Zihnin berraklığı, hayatın kalitesidir.",
  "Tarafsızlık, adaletin temelidir.",
  "Zamanını neye harcadığına dikkat et; hayatın odur.",
  "Soru sormayan, öğrenemez.",
  "Bilgi, kullanıldıkça değer kazanır.",
  "Sabır, aklın sığınağıdır.",
  "Kendi sınırlarını bilmek, gerçek bilgeliktir.",
  "Esnek olan kırılmaz, bükülür.",
  "Yanılmak insancadır, ama ders almamak hatadır.",
  "Akıllı olan, kendi hatalarını görür.",
  "Odaklanmış zihin, en keskin kılıçtan güçlüdür.",
  "Dürüstlük, en yüksek bilgeliktir.",
  "Öğrenmeyi bırakan yaşlanır.",
  "Derin nefes al, derin düşün.",
  "Sessiz bir zihin, evrenin sesini duyar.",
  "Gelecek, bilgiyle inşa edilir.",
  "Yanlış giden bir şeyi düzeltmek cesaret ister.",
  "Bilge kişi, ne zaman susacağını bilir.",
  "Gerçek şıkırtı, bilginin derinliğindedir.",
  "Akıl, duyguların dengesidir.",
  "Bir adımı atmadan önce basacağın yeri gör.",
  "Öğrenmek sınır tanımaz.",
  "Düşünmeden atılan adım, pişmanlığa çıkar.",
  "Zihinsel esneklik, hayatta kalmanın anahtarıdır.",
  "Anlamak, bağ kurmaktır.",
  "Bilgelik, hayatı zarafetle yaşamaktır.",
  "Dost, karanlıkta yanına oturandır.",
  "Kalp kırmak, bir dünyayı yıkmaya benzer.",
  "Güven, cam gibidir; bir kez kırıldı mı eskisi gibi olmaz.",
  "Nezaket, her kapıyı açan çil çil anahtardır.",
  "Bir tebessüm, bin hüzne iyi gelir.",
  "Gerçek dost, arkandan konuşmayan, yüzüne söyleyendir.",
  "Vefa, insanın alnındaki en güzel süstür.",
  "Dinlemek, karşıdakine verilen en güzel hediyedir.",
  "Empati, başkasının gözüyle bakabilmektir.",
  "Kalpten çıkan söz, kalbe ulaşır.",
  "İnsan, dostunun aynasıdır.",
  "Bir tatlı söz, kış ortasında bahar yaratır.",
  "Paylaşmak, mutluluğu ikiye katlar.",
  "İncelik, ruhun zarafetidir.",
  "Dostluk, mesafelerle azalmaz.",
  "Birlik olmak, yükü hafifletir.",
  "Samimiyet, en güçlü dildir.",
  "Dürüst bir düşman, yalancı bir dosttan hayırlıdır.",
  "Kalbi kırık olanın duası sessizdir.",
  "İnsanları dinlemeyi öğren, hayat sana çok şey öğretir.",
  "Güler yüz, sadakadır.",
  "Bir başkasının mutluluğuyla mutlu olmak en büyük erdemdir.",
  "Sözünün eri olmak, karakterin temelidir.",
  "Anlayış, sevginin temelidir.",
  "Dostluk, bir ruhun iki ayrı bedende yaşamasıdır.",
  "Affetmek, geçmişi değiştirmez ama geleceğin önünü açar.",
  "Kıymet bilmek, kaybetmeden önce yapılması gereken bir şeydir.",
  "Cömertlik, malın değil, kalbin büyüklüğüdür.",
  "Gerçek dostluklar zamanla demlenir.",
  "Kalbin temizse, gözlerin parlar.",
  "İnsan, biriktirdiği dostlar kadardır.",
  "Sevgi, paylaştıkça büyüyen tek şeydir.",
  "Kıskançlık, başkasının ışığını söndürmeye çalışmaktır.",
  "Saygı, sevginin en sağlam temelidir.",
  "Güven kazanmak yıllar alır, kaybetmek bir saniye.",
  "Yüreği geniş olanın evi de geniş olur.",
  "Birlikte gülmek güzeldir, birlikte ağlayabilmek dostluktur.",
  "Nezaket, zayıflık değil; güçtür.",
  "Bir insana verilebilecek en büyük değer, zamandır.",
  "Tatlı dil, yılanı deliğinden çıkarır.",
  "Yalancının mumu yatsıya kadar yanar.",
  "Dürüstlük pahalı bir hediyedir; ucuz insanlardan beklenmez.",
  "Samimi bir kucaklaşma, bin kelimeden değerlidir.",
  "Dostunun derdiyle dertlenmeyen dost değildir.",
  "Kalbinin kapısını iyiliğe aç.",
  "Başkalarını anlamak bilgelik, kendini anlamak aydınlanmadır.",
  "Birlikte yürümek, yalnız yürümekten daha kolaydır.",
  "Hoşgörü, ruhun genişliğidir.",
  "Her insan bir dünyadır; keşfetmesini bil.",
  "Kötülüğe iyilikle karşılık vermek erdemdir.",
  "İnsan bağ kurduğu kadar yaşar.",
  "Gerçek bağlar gözle görülmez, hissedilir.",
  "Gönül almak, bir ömre bedeldir.",
  "Dostluk, zor zamanların sınavıdır.",
  "Kırılan kalp iyileşir, ama izi kalır.",
  "Güven, ilişkinin çimentosudur.",
  "Bir gülüşün değiştiremeyeceği şey azdır.",
  "İyilik yap, denize at; balık bilmezse Hâlik bilir.",
  "Söz veriyorsan, arkasında dur.",
  "Sevgiyle bakılan her şey güzel görünür.",
  "Gerçek insanlık, zayıfa gösterilen merhamettedir.",
  "Bir insanı değiştiremezsin, ancak sevebilirsin.",
  "Dedikodu, küçük zihinlerin eğlencesidir.",
  "Dostun varlığı, en büyük servettir.",
  "Kalbine iyilik ek, iyilik biçersin.",
  "İnsan inceldiği yerden değil, koptuğu yerden anlaşılır.",
  "Saygının olmadığı yerde sevgi uzun sürmez.",
  "Yalnızlık bir tercih olabilir, ama dostluk bir ihtiyaçtır.",
  "Bencil insan, kendi gölgesinde kaybolur.",
  "Anlayışlı olmak, dinlemekle başlar.",
  "Dost, kusurları örten örtüdür.",
  "İnsan olmak, dertlere duyarsız kalmamaktır.",
  "Gönülden gönüle bir yol vardır.",
  "Tebessüm, evrensel bir dildir.",
  "Başkasının yükünü hafifleten, kendi yolunu kolaylaştırır.",
  "Sevgi, kalbin gıdasıdır.",
  "Doğrulukdan ayrılmayan, dostsuz kalmaz.",
  "Yürekten yapılan her iş iz bırakır.",
  "Bir dostun desteği, fırtınada sığınaktır.",
  "İnsan, dokunduğu hayatlar kadar zengindir.",
  "Karakter, kimse bakmadığında ne yaptığına bağlıdır.",
  "Erdem, doğru olanı zor olsa da yapmaktır.",
  "İrade, zihnin kasıdır; çalıştırırsan güçlenir.",
  "Dürüstlük, ruhun en parlak aynasıdır.",
  "Alçakgönüllülük, büyüklüğün şanındandır.",
  "Nefsine hakim olan, dünyaya hakim olur.",
  "Cesaret, korkunun olmaması değil, ona rağmen yürümektir.",
  "Asalet, boyda değil, duruştadır.",
  "Sözü ile özü bir olan insan güvenilirdir.",
  "Disiplin, kendi kendine verdiğin sözü tutmaktır.",
  "Bir insanın karakteri, kriz anında belli olur.",
  "Adalet, mülkün temelidir.",
  "Gurur düşürür, alçakgönüllülük yükseltir.",
  "Güçlü insan, duygularını yöneten insandır.",
  "Temiz bir vicdan, en yumuşak yastıktır.",
  "Sabır, ruhun gücünü gösterir.",
  "Kendine saygısı olan, başkasına da saygı duyar.",
  "Hırs gözü kör eder, azim ise yolu açar.",
  "Küçük şeylerde dürüst olmayan, büyük şeylerde de olamaz.",
  "Öfkenin kazananı yoktur.",
  "Olgun insan, az konuşur, çok iş yapar.",
  "Kararlılık, engelleri eritir.",
  "Gerçek özgürlük, bağımlılıklardan kurtulmaktır.",
  "Merhamet, kalbin inceliğidir.",
  "Kibirden uzak dur, küçülürsün.",
  "Utanma duygusu, insanın ziynetidir.",
  "Doğruluk, her zaman en kısa yoldur.",
  "İrade gücü, alışkanlıkların efendisidir.",
  "Kendine hakim olan, başkasına boyun eğmez.",
  "Karakter, zamanla inşa edilir.",
  "Dik durmak, kibirlenmek demek değildir.",
  "Özür dilemek, büyüklük göstergesidir.",
  "Şeref, paradan daha değerlidir.",
  "Sözünde durmak, sadakatin kanıtıdır.",
  "Hoşgörülü olmak, olgunluğun işaretidir.",
  "Vicdan, içimizdeki en adil yargıçtır.",
  "Tutarlılık, güven yaratır.",
  "Küçük hesaplar yapan, büyük resmi göremez.",
  "Karakterini satmayan insan zengindir.",
  "Nezaket, eğitimli olmanın göstergesidir.",
  "Özsaygı, başarının ilk adımıdır.",
  "Eğilmeyen ağaç kırılır, bükülen fırtınayı atlatır.",
  "Hak yemek, geleceğini karartmaktır.",
  "Cesur adımlar, büyük izler bırakır.",
  "Cömert insan, verdiğinden eksilmez.",
  "Sabırlı insan, zaferi garantiler.",
  "Karakter, verdiğin kararlarda gizlidir.",
  "Kendi ışığına güven, gölgelerden korkma.",
  "Mütevazı olmak, değerini düşürmez.",
  "İçindeki sesi dinle, o sana doğruyu söyler.",
  "Haksızlığa karşı durmak, en büyük erdemdir.",
  "Güçlü bir irade, dağı bile yerinden oynatır.",
  "Yaşadığın gibi inan, inandığın gibi yaşa.",
  "Yalanın ömrü kısadır, gerçeğin sonsuz.",
  "Sözün arkasında durmak, insan olmanın gereğidir.",
  "Kıskançlık, kendi kendini yemek demektir.",
  "Sadakat, en kıymetli hazinedir.",
  "İyilik, gizli yapıldığında daha değerlidir.",
  "Karakter, zorluklar karşısındaki duruşundur.",
  "Zayıflığını kabul etmek, güçlü olmanın ilk adımıdır.",
  "Verilen söz, borçtur.",
  "İnsanı yükselten erdemleridir.",
  "Kararlı bir adım, kararsız bin adımdan iyidir.",
  "Adaletli ol ki saygı göresin.",
  "Nefsini yenen, her şeyi yener.",
  "Saygı, zorla alınmaz, kazanılır.",
  "Korkak, bin kez ölür; cesur, bir kez.",
  "Karakter, rüzgarda savrulmayan yapraktır.",
  "Kendi değerini başkasının ölçüsüyle belirleme.",
  "Dürüstlük, en güvenli limandır.",
  "İyilik yapmak, ruhu besler.",
  "Güçlü olmak, düşmemek değil, her düştüğünde kalkmaktır.",
  "Kibirden kaçınan, sevilir.",
  "Verilen emek asla zayi olmaz.",
  "Karakter, fırtınalı günde belli olur.",
  "Hoşgörü, kardeşliğin anahtarıdır.",
  "Temiz kalpli olmak, dünyaya sunabileceğin en güzel şeydir.",
  "İrade, zor olanı seçebilme gücüdür.",
  "Kendine dürüst olmayan, başkasına olamaz.",
  "Erdemli insan, zamana yenilmez.",
  "Umut, geleceğin ilk ışığıdır.",
  "Değişim, cesaret edenlerle başlar.",
  "Zaman, harcadığın değil, yatırdığın şeydir.",
  "Bugün atılan adım, yarının temeli olur.",
  "Her yeni gün, yeni bir fırsattır.",
  "Umudunu kaybeden, her şeyini kaybeder.",
  "Değişime direnç göstermek, rüzgara karşı koşmaya benzer.",
  "Zaman geri gelmez, kıymetini bil.",
  "Gelecek, umudunu koruyanlarındır.",
  "Karanlık, ışığın habercisidir.",
  "Bir fidan dikmek, geleceğe umut ekmektir.",
  "Değişim, zihinde başlar, hayatta biter.",
  "Geçmişe takılı kalan, geleceği kaçırır.",
  "Anı yaşa, çünkü sadece şu an var.",
  "Her kışın arkasından bahar gelir.",
  "Umut, ruhun gıdasıdır.",
  "Zamana değer vermek, kendine değer vermektir.",
  "Eski alışkanlıklar, yeni yollar açmaz.",
  "Yenilenmek, canlı kalmaktır.",
  "Umut, içindeki hiç sönmeyen ateştir.",
  "Zaman her şeyin ilacıdır, ama doğru kullanılırsa.",
  "Değişmeyen tek şey değişimin kendisidir.",
  "Yarın, yeni bir hikaye yazmak için şanstır.",
  "Hayat akıp gidiyor; durup izleme, dahil ol.",
  "Bir mucize bekleme, mucize sen ol.",
  "Umudun olduğu yerde yaşam vardır.",
  "Dünü unut, bugünü yaşa, yarını inşa et.",
  "Zaman, satılmayan tek değerdir.",
  "Kendini değiştiren, dünyayı değiştirir.",
  "Her başlangıç bir umuttur.",
  "Gözlerini geleceğe dik, geçmiş sana yön veremez.",
  "Zamanı boşa harcamak, hayatı boşa harcamaktır.",
  "Rüzgarın yönünü değiştiremiyorsan, yelkenlerini ayarla.",
  "Umut var oldukça yol bitmez.",
  "Değişim zor olabilir, ama yerinde saymak öldürür.",
  "Bir gün değil, her gün ilerle.",
  "Gelecek, bugün ne yaptığına bağlıdır.",
  "Zamana meydan okumak, üretmektir.",
  "Yıkılanın yerine yenisi inşa edilir.",
  "Umudunu kaybetme, kapı en beklemediğin anda açılır.",
  "Değişim, konfor alanının bittiği yerde başlar.",
  "Zaman akar, iz bırakan kalır.",
  "Her yeni sabah, temiz bir sayfadır.",
  "Hayal kurmak, geleceği tasarlamaktır.",
  "Umut, karanlıkta yol gösteren yıldızdır.",
  "Geçmişi kabul et, geleceğe odaklan.",
  "Zaman en büyük öğretmendir.",
  "Kendini yenilemeyen, eskinin gölgesinde kalır.",
  "Bir kıvılcım, büyük bir yangın başlatabilir.",
  "Umut etmek, inanmanın ilk adımıdır.",
  "Zamanı durduramazsın, ama doğru yönetebilirsin.",
  "Değişim, gelişim kapısını açar.",
  "Hayat, yeniliklere kucak açtıkça güzelleşir.",
  "Umudunu kaybetmiş bir kalp, canlı değildir.",
  "Geçmiş tecrübe, gelecek hedeftir.",
  "Zamana ayak uyduramayan, geride kalır.",
  "Yeni bir gün, yeni bir enerjidir.",
  "Gelecek, cesur kararlar alanlarındır.",
  "Umut, engelleri aşma gücü verir.",
  "Zamanını boşa harcama, o senin hayatındır.",
  "Değişime açık olmak, esnekliktir.",
  "Yolu yürümeye devam et, ışık yakındır.",
  "Her büyük başarı, bir umutla başladı.",
  "Geçmişi değiştiremezsin, ama yarını seçebilirsin.",
  "Zaman, en adil sermayedir; herkese eşit verilir.",
  "Yenilikten korkma, durağanlıktan kork.",
  "Umut, ruhun pusulasıdır.",
  "Bir adım at, yol sana görünür.",
  "Zamanını yöneten, geleceğini yönetir.",
  "Değişim bir gecede olmaz, ama bir kararla başlar.",
  "Gelecek, bugün yaptıklarının eseridir.",
  "Umut, içimizdeki sönmeyen fenerdir.",
  "Zamanı iyi değerlendirmek, bilgeliktir.",
  "Eski düşüncelerle yeni kapılar açılmaz.",
  "Gün doğmadan neler doğar.",
  "Umut, zorluklara karşı en büyük silahtır.",
  "Zaman bir nehirdir; aynı suda iki kez yıkanılmaz.",
  "Değişimi kucakla, gelişimi hisset.",
  "Bugün yapacağın seçim, yarınki yaşamındır.",
  "Hayal ettiğin sürece gençsin.",
  "Umutsuzluk, ruhun zindanına girmektir.",
  "Zaman harcama, zaman üret.",
  "Dönüşüm, cesaretle başlar.",
  "Geleceğe güvenle bakmak, bugünü iyi yaşamaktır.",
  "Umut, en zor günde bile gülümsemektir.",
  "Zamanın değerini en çok kaybeden bilir.",
  "Değişim, kelebeğin kozasından çıkmasıdır.",
  "Yola çıkana yol açılır.",
  "Umudunu taze tut, hayat sürprizlerle doludur.",
  "Zamanı durduramayız, ama iz bırakabiliriz.",
  "Yeniden başlamak için hiçbir zaman geç değildir.",
  "Değişime uyum sağlayan hayatta kalır.",
  "Umut, yarının kapısını açan anahtardır.",
  "Geçmiş bir anı, gelecek bir hayaldir; şu an ise gerçektir.",
  "Zamanını en iyi şekilde kullan; hayat kısadır.",
  "Her gün yeni bir öğrenme fırsatıdır.",
  "Umut etmekten asla vazgeçme.",
  "Geleceğini inşa etmek senin elinde.",
  "Zaman, boşa harcanamayacak kadar kıymetlidir.",
  "Son söz söylenene kadar umut daima vardır.",
];
